### ISSUE TITLE
Issue with changing server

### ISSUE THREAD

**Issue by Resmi-Suresh** [Petrarolo/PIdata#2]
I installed using pip install PIdata recently. Although I am able to download PI data from the default server, I am unable to add the server as one of the input to the function and download the data. Error: got an unexpected keyword argument 'server'.
 It is mentioned in the code that it is now revised to include this provision now.

**Comment by Petrarolo** [comment]
Hi @Resmi-Suresh, 

Thanks for raising the issue (and using PIdata)! You are correct. It seems like the pip version is out of date. I will rebuild it and then let you know when you can update.

**Comment by Petrarolo** [comment]
PIdata version 0.3.1 is now available. It includes the ability to change server. I have also added some updates to the documentation. @Resmi-Suresh updating should fix the problem: 

`pip install PIdata --upgrade`
